name: Build Docker Image

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Database connection setup
      run: echo "DB_CONN_STRING=${{ secrets.DB_CONN_STRING }}" >> "$GITHUB_ENV"
    - name: Build the Docker image
      run: docker build . -t fifa-api-image:$(date +%s)
